[build]
  command = "npm install --include=dev && npm run build:web"
  publish = "dist"
  environment = { NODE_VERSION = "20", VITE_POSTHOG_API_KEY = "${VITE_POSTHOG_API_KEY}", VITE_POSTHOG_HOST = "${VITE_POSTHOG_HOST}" }

[[headers]]
  for = "*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/tesseract/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/tessdata/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
