/**
 * PDF Analyzer for Litera markup detection
 * 
 * Analyzes PDF files generated by Litera Compare for Word to extract
 * text with proper insertion/deletion markup based on PDF graphics operations.
 */

class PdfAnalyzer {
    constructor() {
        this.pdfjsLib = null;
        this.isInitialized = false;
    }

    /**
     * Initialize PDF.js library
     */
    async initialize() {
        if (this.isInitialized) return;
        
        // PDF.js should be loaded from CDN in the HTML
        if (typeof pdfjsLib === 'undefined') {
            throw new Error('PDF.js library not found. Make sure it is loaded from CDN.');
        }
        
        this.pdfjsLib = pdfjsLib;
        
        // Set worker source
        this.pdfjsLib.GlobalWorkerOptions.workerSrc = 
            'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
        
        this.isInitialized = true;
        console.log('PDF Analyzer initialized');
    }

    /**
     * Analyze a PDF file and extract styled text with Litera markup
     * @param {File} file - PDF file to analyze
     * @returns {Promise<{summary: Object, styledText: Array}>} - Parsed content
     */
    async analyzePdf(file) {
        await this.initialize();
        
        return new Promise((resolve, reject) => {
            const fileReader = new FileReader();
            
            fileReader.onload = async () => {
                try {
                    const typedArray = new Uint8Array(fileReader.result);
                    const pdf = await this.pdfjsLib.getDocument(typedArray).promise;
                    
                    console.log(`PDF loaded. Pages: ${pdf.numPages}`);
                    
                    // Extract summary information (usually on first page)
                    const summary = await this.extractSummaryInfo(pdf);
                    
                    // Process all pages for styled text and annotations
                    const textAnalysis = await this.extractStyledText(pdf);
                    
                    resolve({
                        summary,
                        styledText: textAnalysis.styledText,
                        annotations: textAnalysis.annotations,
                        pageCount: pdf.numPages
                    });
                    
                } catch (error) {
                    console.error('PDF analysis failed:', error);
                    reject(error);
                }
            };
            
            fileReader.onerror = () => reject(new Error('Failed to read PDF file'));
            fileReader.readAsArrayBuffer(file);
        });
    }

    /**
     * Extract summary information from Litera report (usually first page)
     */
    async extractSummaryInfo(pdf) {
        try {
            const page = await pdf.getPage(1);
            const textContent = await page.getTextContent();
            
            const summary = {
                tool: 'Unknown',
                originalFilename: '',
                modifiedFilename: '',
                totalChanges: 0,
                additions: 0,
                deletions: 0,
                formatChanges: 0
            };
            
            // Look for specific Litera patterns in text
            const allText = textContent.items.map(item => item.str).join(' ');
            
            // Extract tool name
            const toolMatch = allText.match(/Litera Compare for Word ([\d.]+)/i);
            if (toolMatch) {
                summary.tool = `Litera Compare for Word ${toolMatch[1]}`;
            }
            
            // Extract filenames
            const origMatch = allText.match(/Original filename:\s*([^\n\r]+)/i);
            if (origMatch) {
                summary.originalFilename = origMatch[1].trim();
            }
            
            const modMatch = allText.match(/Modified filename:\s*([^\n\r]+)/i);
            if (modMatch) {
                summary.modifiedFilename = modMatch[1].trim();
            }
            
            // Extract change counts
            const addMatch = allText.match(/Add[^\d]*(\d+)/i);
            if (addMatch) {
                summary.additions = parseInt(addMatch[1], 10);
            }
            
            const delMatch = allText.match(/Delete[^\d]*(\d+)/i);
            if (delMatch) {
                summary.deletions = parseInt(delMatch[1], 10);
            }
            
            const totalMatch = allText.match(/Total Changes[^\d]*(\d+)/i);
            if (totalMatch) {
                summary.totalChanges = parseInt(totalMatch[1], 10);
            }
            
            return summary;
            
        } catch (error) {
            console.warn('Could not extract summary info:', error);
            return { tool: 'Litera Compare', totalChanges: 0 };
        }
    }

    /**
     * Extract styled text from all pages using graphics line detection
     */
    async extractStyledText(pdf) {
        const allStyledText = [];
        const allAnnotations = [];
        
        for (let i = 1; i <= pdf.numPages; i++) {
            try {
                const page = await pdf.getPage(i);
                const textContent = await page.getTextContent();
                const operatorList = await page.getOperatorList();
                const viewport = page.getViewport({ scale: 1.0 });
                
                // Use proven graphics line detection approach
                const lines = this.parseLinesFromOps(operatorList, viewport);
                const textAnalysis = this.analyzeTextWithLines(textContent, lines);
                
                // Add page number to each text item
                const pageStyledText = textAnalysis.map(item => ({
                    ...item,
                    page: i
                }));
                
                allStyledText.push(...pageStyledText);
                
                // Extract annotations separately for the comments table
                try {
                    const annotations = await page.getAnnotations();
                    
                    // DEBUG: Show all annotations found - ENHANCED DEBUGGING
                    console.log(`=== PAGE ${i} ANNOTATION EXTRACTION ===`);
                    console.log(`Raw annotations found: ${annotations.length}`);
                    
                    // Show ALL annotations with full debugging details
                    if (annotations.length > 0) {
                        for (let j = 0; j < annotations.length; j++) {
                            const ann = annotations[j];
                            console.log(`Annotation ${j} (page ${i}):`, {
                                subtype: ann.subtype,
                                annotationType: ann.annotationType,
                                contents: ann.contents,
                                title: ann.title,
                                user: ann.user,
                                richText: ann.richText,
                                rect: ann.rect,
                                hasPopup: ann.hasPopup,
                                parentId: ann.parentId,
                                parentType: ann.parentType,
                                flags: ann.flags,
                                color: ann.color,
                                allProps: Object.keys(ann)
                            });
                        }
                    } else {
                        // Even if no annotations, show what getAnnotations() returns
                        console.log(`No annotations found on page ${i}. Type of result:`, typeof annotations);
                        console.log(`Is array?`, Array.isArray(annotations));
                    }
                    
                    console.log('=== END ANNOTATION DEBUG ===');
                    
                    for (const annotation of annotations) {
                        if (this.isCommentAnnotation(annotation)) {
                            allAnnotations.push({
                                page: i,
                                author: annotation.title || annotation.user || 'Unknown',
                                text: annotation.contents || annotation.richText || '',
                                type: annotation.subtype || 'Comment',
                                rect: annotation.rect || []
                            });
                        }
                    }
                } catch (annotError) {
                    console.warn(`Could not extract annotations from page ${i}:`, annotError);
                }
                
            } catch (error) {
                console.warn(`Error processing page ${i}:`, error);
            }
        }
        
        // Debug logging to help understand what's being detected
        console.log(`Extracted ${allStyledText.length} text items and ${allAnnotations.length} annotations`);
        
        const styleStats = allStyledText.reduce((stats, item) => {
            stats[item.style] = (stats[item.style] || 0) + 1;
            return stats;
        }, {});
        
        console.log('Style distribution:', styleStats);
        
        if (allAnnotations.length > 0) {
            console.log('Sample annotations:', allAnnotations.slice(0, 3));
        }
        
        // DEBUG: Show sample text items with all available properties
        console.log('=== DEBUGGING TEXT ITEMS ===');
        const sampleItems = allStyledText.slice(0, 5);
        for (let i = 0; i < sampleItems.length; i++) {
            const item = sampleItems[i];
            console.log(`Item ${i}:`, {
                text: item.text,
                style: item.style,
                fontName: item.fontName,
                fontSize: item.fontSize,
                transform: item.transform,
                // Show all available properties
                allProps: Object.keys(item)
            });
        }
        console.log('=== END DEBUG ===');
        
        return { styledText: allStyledText, annotations: allAnnotations };
    }

    /**
     * Check if an annotation should be treated as a comment - ENHANCED VERSION
     */
    isCommentAnnotation(annotation) {
        if (!annotation) return false;
        
        console.log('Checking annotation for comment status:', {
            subtype: annotation.subtype,
            annotationType: annotation.annotationType,
            contents: annotation.contents,
            title: annotation.title,
            hasContent: !!(annotation.contents && annotation.contents.trim())
        });
        
        // Check if annotation has meaningful content
        const hasContent = (annotation.contents && annotation.contents.trim()) || 
                          (annotation.richText && String(annotation.richText).trim());
        
        if (!hasContent) {
            console.log('-> Rejected: No meaningful content');
            return false;
        }
        
        // Include common comment annotation types - EXPANDED LIST
        const commentTypes = [
            'Text', 'FreeText', 'Note', 'Comment', 'Highlight', 
            'StrikeOut', 'Underline', 'Popup', 'Widget',
            'Ink', 'Line', 'Square', 'Circle', 'Polygon',
            'PolyLine', 'Squiggly', 'Caret', 'FileAttachment'
        ];
        
        const subtype = annotation.subtype || annotation.annotationType || '';
        
        const isCommentType = commentTypes.includes(subtype) || subtype.includes('Comment');
        
        console.log(`-> ${isCommentType ? 'ACCEPTED' : 'REJECTED'} as comment (subtype: ${subtype})`);
        
        return isCommentType;
    }

    /**
     * Parse graphics operations to extract horizontal lines (underlines/strikethroughs)
     * Based on proven working implementation from reference code
     */
    parseLinesFromOps(opList, viewport) {
        const lines = [];
        const H_TOL = 1.0; // Tolerance for horizontal lines
        
        // Track graphics state
        let strokeRGB = [0, 0, 0]; // Default black
        let lineWidth = 1;
        
        console.log(`=== PARSING LINES FROM ${opList.fnArray.length} OPERATIONS ===`);
        
        for (let i = 0; i < opList.fnArray.length; i++) {
            const fn = opList.fnArray[i];
            const args = opList.argsArray[i];
            
            // Track stroke color changes
            if (fn === this.pdfjsLib.OPS.setStrokeRGBColor && args.length >= 3) {
                strokeRGB = [args[0], args[1], args[2]];
            }
            
            // Track line width
            if (fn === this.pdfjsLib.OPS.setLineWidth && args.length >= 1) {
                lineWidth = args[0];
            }
            
            // Look for path construction operations
            if (fn === this.pdfjsLib.OPS.constructPath && args.length >= 2) {
                const pathOps = args[0];
                const pathArgs = args[1];
                
                // Look for moveTo -> lineTo sequences (simple lines)
                if (pathOps.length === 2 && 
                    pathOps[0] === this.pdfjsLib.OPS.moveTo && 
                    pathOps[1] === this.pdfjsLib.OPS.lineTo) {
                    
                    // Get start and end points
                    const start = viewport.convertToViewportPoint(pathArgs[0], pathArgs[1]);
                    const end = viewport.convertToViewportPoint(pathArgs[2], pathArgs[3]);
                    
                    const startY = start[1];
                    const endY = end[1];
                    
                    // Check if this is approximately horizontal
                    if (Math.abs(startY - endY) <= H_TOL) {
                        const lineColor = this.classifyLineColor(strokeRGB[0], strokeRGB[1], strokeRGB[2]);
                        
                        lines.push({
                            x1: start[0],
                            y1: start[1], 
                            x2: end[0],
                            y2: end[1],
                            r: strokeRGB[0],
                            g: strokeRGB[1], 
                            b: strokeRGB[2],
                            width: lineWidth,
                            typeHint: lineColor
                        });
                    }
                }
            }
        }
        
        console.log(`Found ${lines.length} horizontal lines`);
        if (lines.length > 0) {
            console.log('Sample lines:', lines.slice(0, 3).map(line => ({
                coords: `(${line.x1.toFixed(1)}, ${line.y1.toFixed(1)}) -> (${line.x2.toFixed(1)}, ${line.y2.toFixed(1)})`,
                color: `rgb(${line.r.toFixed(2)}, ${line.g.toFixed(2)}, ${line.b.toFixed(2)})`,
                typeHint: line.typeHint
            })));
        }
        
        return lines;
    }
    
    /**
     * Classify line color to determine if it's insertion (green) or deletion (red)
     */
    classifyLineColor(r, g, b) {
        // Based on working reference code color classification
        const rDom = Math.max(0, r - Math.max(g, b));
        const gDom = Math.max(0, g - Math.max(r, b));
        
        const isRed = rDom >= 0.18 && r > 0.4;
        const isGreen = gDom >= 0.18 && g > 0.4;
        
        if (isRed) return 'del';
        if (isGreen) return 'ins'; 
        return 'unknown';
    }
    
    /**
     * Match text items with detected lines to determine track change styling
     */
    analyzeTextWithLines(textContent, lines) {
        const textAnalysis = [];
        
        console.log(`=== MATCHING ${textContent.items.length} TEXT ITEMS WITH ${lines.length} LINES ===`);
        
        for (const item of textContent.items) {
            const style = this.checkStyle(item, lines);
            
            textAnalysis.push({
                text: item.str,
                style: style,
                transform: item.transform,
                fontName: item.fontName || '',
                fontSize: item.fontSize || 0,
                width: item.width || 0,
                height: item.height || 0
            });
        }
        
        return textAnalysis;
    }
    
    /**
     * Check if text item matches any lines (underline/strikethrough)
     * Based on proven working algorithm with proper tolerances
     */
    checkStyle(textItem, lines) {
        if (!lines || lines.length === 0) return 'equal';
        
        const transform = textItem.transform;
        const x = transform[4];
        const y = transform[5];
        const width = textItem.width || 0;
        const height = textItem.height || 0;
        
        if (width <= 0 || height <= 0) return 'equal';
        
        // Calculate baseline and midline positions based on working code
        const baselineY = y + height * 0.06;  // Underline position
        const midlineY = y + height * 0.52;   // Strikethrough position
        
        let bestMatch = null;
        let bestScore = 0;
        
        for (const line of lines) {
            // Check horizontal overlap - require minimum 35% overlap
            const overlapStart = Math.max(x, line.x1);
            const overlapEnd = Math.min(x + width, line.x2);
            const overlap = Math.max(0, overlapEnd - overlapStart);
            const overlapFraction = overlap / Math.max(1, width);
            
            if (overlapFraction < 0.35) continue; // Minimum overlap requirement
            
            // Check vertical alignment for underline (insertion)
            const underlineDist = Math.abs(line.y1 - baselineY);
            const underlineTolerance = Math.max(2.0, height * 0.3);
            
            // Check vertical alignment for strikethrough (deletion) 
            const strikethroughDist = Math.abs(line.y1 - midlineY);
            const strikethroughTolerance = Math.max(2.0, height * 0.4);
            
            // Score this line match
            let score = overlapFraction;
            let matchType = 'equal';
            
            if (underlineDist <= underlineTolerance) {
                score += 1.0 - (underlineDist / underlineTolerance);
                matchType = 'ins';
                
                // Color bonus for green lines
                if (line.typeHint === 'ins') {
                    score += 0.5;
                }
            } else if (strikethroughDist <= strikethroughTolerance) {
                score += 1.0 - (strikethroughDist / strikethroughTolerance);
                matchType = 'del';
                
                // Color bonus for red lines
                if (line.typeHint === 'del') {
                    score += 0.5;
                }
            }
            
            if (score > bestScore && matchType !== 'equal') {
                bestScore = score;
                bestMatch = matchType;
            }
        }
        
        return bestMatch || 'equal';
    }


    /**
     * Generate HTML diff from styled text for further processing
     */
    generateHtmlDiff(styledText) {
        // Sort text items by position to reconstruct reading order
        const sortedText = [...styledText].sort((a, b) => {
            const y1 = a.transform[5];
            const y2 = b.transform[5];
            const x1 = a.transform[4];
            const x2 = b.transform[4];
            
            // First sort by Y (top to bottom, but PDF Y is inverted)
            if (Math.abs(y1 - y2) > 8) { // Different lines
                return y2 - y1; // Higher Y coordinate comes first in PDF
            } else {
                // Same line, sort by X (left to right)
                return x1 - x2;
            }
        });
        
        let html = '<div style="font-family: serif; white-space: pre-wrap;">';
        let currentLineY = null;
        let addedSpacing = false;
        
        sortedText.forEach((item, index) => {
            const y = item.transform[5];
            const text = this.escapeHtml(item.text);
            
            // Add line breaks for new lines
            if (currentLineY !== null && Math.abs(y - currentLineY) > 8) {
                html += '<br>\n';
                addedSpacing = true;
            }
            
            // Add spacing between words on same line
            if (index > 0 && !addedSpacing && currentLineY !== null && 
                Math.abs(y - currentLineY) <= 8) {
                html += ' ';
            }
            
            currentLineY = y;
            addedSpacing = false;
            
            // Wrap text based on detected style
            if (item.style === 'ins') {
                html += `<span style="text-decoration: underline; color: #16a34a;">${text}</span>`;
            } else if (item.style === 'del') {
                html += `<span style="text-decoration: line-through; color: #dc2626;">${text}</span>`;
            } else {
                html += text;
            }
        });
        
        html += '</div>';
        return html;
    }

    /**
     * Escape HTML special characters
     */
    escapeHtml(text) {
        return text
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    }
}

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = PdfAnalyzer;
} else {
    window.PdfAnalyzer = PdfAnalyzer;
}