/**
 * PDF Analyzer for Litera markup detection
 * 
 * Analyzes PDF files generated by Litera Compare for Word to extract
 * text with proper insertion/deletion markup based on PDF graphics operations.
 */

class PdfAnalyzer {
    constructor() {
        this.pdfjsLib = null;
        this.isInitialized = false;
    }

    /**
     * Initialize PDF.js library
     */
    async initialize() {
        if (this.isInitialized) return;
        
        // PDF.js should be loaded from CDN in the HTML
        if (typeof pdfjsLib === 'undefined') {
            throw new Error('PDF.js library not found. Make sure it is loaded from CDN.');
        }
        
        this.pdfjsLib = pdfjsLib;
        
        // Set worker source
        this.pdfjsLib.GlobalWorkerOptions.workerSrc = 
            'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
        
        this.isInitialized = true;
        console.log('PDF Analyzer initialized');
    }

    /**
     * Analyze a PDF file and extract styled text with Litera markup
     * @param {File} file - PDF file to analyze
     * @returns {Promise<{summary: Object, styledText: Array}>} - Parsed content
     */
    async analyzePdf(file) {
        await this.initialize();
        
        return new Promise((resolve, reject) => {
            const fileReader = new FileReader();
            
            fileReader.onload = async () => {
                try {
                    const typedArray = new Uint8Array(fileReader.result);
                    const pdf = await this.pdfjsLib.getDocument(typedArray).promise;
                    
                    console.log(`PDF loaded. Pages: ${pdf.numPages}`);
                    
                    // Extract summary information (usually on first page)
                    const summary = await this.extractSummaryInfo(pdf);
                    
                    // Process all pages for styled text and annotations
                    const textAnalysis = await this.extractStyledText(pdf);
                    
                    resolve({
                        summary,
                        styledText: textAnalysis.styledText,
                        annotations: textAnalysis.annotations,
                        pageCount: pdf.numPages
                    });
                    
                } catch (error) {
                    console.error('PDF analysis failed:', error);
                    reject(error);
                }
            };
            
            fileReader.onerror = () => reject(new Error('Failed to read PDF file'));
            fileReader.readAsArrayBuffer(file);
        });
    }

    /**
     * Extract summary information from Litera report (usually first page)
     */
    async extractSummaryInfo(pdf) {
        try {
            const page = await pdf.getPage(1);
            const textContent = await page.getTextContent();
            
            const summary = {
                tool: 'Unknown',
                originalFilename: '',
                modifiedFilename: '',
                totalChanges: 0,
                additions: 0,
                deletions: 0,
                formatChanges: 0
            };
            
            // Look for specific Litera patterns in text
            const allText = textContent.items.map(item => item.str).join(' ');
            
            // Extract tool name
            const toolMatch = allText.match(/Litera Compare for Word ([\d.]+)/i);
            if (toolMatch) {
                summary.tool = `Litera Compare for Word ${toolMatch[1]}`;
            }
            
            // Extract filenames
            const origMatch = allText.match(/Original filename:\s*([^\n\r]+)/i);
            if (origMatch) {
                summary.originalFilename = origMatch[1].trim();
            }
            
            const modMatch = allText.match(/Modified filename:\s*([^\n\r]+)/i);
            if (modMatch) {
                summary.modifiedFilename = modMatch[1].trim();
            }
            
            // Extract change counts
            const addMatch = allText.match(/Add[^\d]*(\d+)/i);
            if (addMatch) {
                summary.additions = parseInt(addMatch[1], 10);
            }
            
            const delMatch = allText.match(/Delete[^\d]*(\d+)/i);
            if (delMatch) {
                summary.deletions = parseInt(delMatch[1], 10);
            }
            
            const totalMatch = allText.match(/Total Changes[^\d]*(\d+)/i);
            if (totalMatch) {
                summary.totalChanges = parseInt(totalMatch[1], 10);
            }
            
            return summary;
            
        } catch (error) {
            console.warn('Could not extract summary info:', error);
            return { tool: 'Litera Compare', totalChanges: 0 };
        }
    }

    /**
     * Extract styled text from all pages using new text-based approach
     */
    async extractStyledText(pdf) {
        const allStyledText = [];
        const allAnnotations = [];
        
        for (let i = 1; i <= pdf.numPages; i++) {
            try {
                const page = await pdf.getPage(i);
                const textContent = await page.getTextContent();
                const operatorList = await page.getOperatorList();
                const viewport = page.getViewport({ scale: 1.0 });
                
                // Use new text formatting analysis instead of graphics lines
                const textAnalysis = this.analyzeTextFormatting(textContent, operatorList, viewport);
                
                // Add page number to each text item
                const pageStyledText = textAnalysis.map(item => ({
                    ...item,
                    page: i
                }));
                
                allStyledText.push(...pageStyledText);
                
                // Extract annotations separately for the comments table
                try {
                    const annotations = await page.getAnnotations();
                    
                    // DEBUG: Show all annotations found
                    if (annotations.length > 0) {
                        console.log(`=== PAGE ${i} ANNOTATIONS ===`);
                        console.log(`Found ${annotations.length} annotations on page ${i}`);
                        for (let j = 0; j < Math.min(3, annotations.length); j++) {
                            const ann = annotations[j];
                            console.log(`Annotation ${j}:`, {
                                subtype: ann.subtype,
                                contents: ann.contents,
                                title: ann.title,
                                user: ann.user,
                                richText: ann.richText,
                                allProps: Object.keys(ann)
                            });
                        }
                        console.log('=== END ANNOTATION DEBUG ===');
                    }
                    
                    for (const annotation of annotations) {
                        if (this.isCommentAnnotation(annotation)) {
                            allAnnotations.push({
                                page: i,
                                author: annotation.title || annotation.user || 'Unknown',
                                text: annotation.contents || annotation.richText || '',
                                type: annotation.subtype || 'Comment',
                                rect: annotation.rect || []
                            });
                        }
                    }
                } catch (annotError) {
                    console.warn(`Could not extract annotations from page ${i}:`, annotError);
                }
                
            } catch (error) {
                console.warn(`Error processing page ${i}:`, error);
            }
        }
        
        // Debug logging to help understand what's being detected
        console.log(`Extracted ${allStyledText.length} text items and ${allAnnotations.length} annotations`);
        
        const styleStats = allStyledText.reduce((stats, item) => {
            stats[item.style] = (stats[item.style] || 0) + 1;
            return stats;
        }, {});
        
        console.log('Style distribution:', styleStats);
        
        if (allAnnotations.length > 0) {
            console.log('Sample annotations:', allAnnotations.slice(0, 3));
        }
        
        // DEBUG: Show sample text items with all available properties
        console.log('=== DEBUGGING TEXT ITEMS ===');
        const sampleItems = allStyledText.slice(0, 5);
        for (let i = 0; i < sampleItems.length; i++) {
            const item = sampleItems[i];
            console.log(`Item ${i}:`, {
                text: item.text,
                style: item.style,
                fontName: item.fontName,
                fontSize: item.fontSize,
                transform: item.transform,
                // Show all available properties
                allProps: Object.keys(item)
            });
        }
        console.log('=== END DEBUG ===');
        
        return { styledText: allStyledText, annotations: allAnnotations };
    }

    /**
     * Check if an annotation should be treated as a comment
     */
    isCommentAnnotation(annotation) {
        if (!annotation) return false;
        
        // Check if annotation has meaningful content
        const hasContent = (annotation.contents && annotation.contents.trim()) || 
                          (annotation.richText && String(annotation.richText).trim());
        
        if (!hasContent) return false;
        
        // Include common comment annotation types
        const commentTypes = ['Text', 'FreeText', 'Note', 'Comment', 'Highlight', 'StrikeOut', 'Underline'];
        const subtype = annotation.subtype || annotation.annotationType || '';
        
        return commentTypes.includes(subtype) || subtype.includes('Comment');
    }

    /**
     * Analyze PDF text styling and formatting to detect track changes
     * Litera uses text properties rather than graphics lines for markup
     */
    analyzeTextFormatting(textContent, operatorList, viewport) {
        const textAnalysis = [];
        
        // DEBUG: Show what PDF.js actually gives us
        if (textContent.items.length > 0) {
            console.log('=== RAW PDF.JS TEXT ITEMS ===');
            const sample = textContent.items.slice(0, 3);
            for (let i = 0; i < sample.length; i++) {
                const item = sample[i];
                console.log(`Raw item ${i}:`, {
                    str: item.str,
                    fontName: item.fontName,
                    fontSize: item.fontSize,
                    transform: item.transform,
                    width: item.width,
                    height: item.height,
                    allProps: Object.keys(item)
                });
            }
            console.log('=== END RAW DEBUG ===');
        }
        
        try {
            // Track graphics state for color/font information
            let currentFont = null;
            let currentFillColor = [0, 0, 0]; // RGB 0-1
            let currentStrokeColor = [0, 0, 0];
            
            // Parse graphics operations to track state changes
            const stateMap = new Map();
            
            for (let i = 0; i < operatorList.fnArray.length; i++) {
                const fn = operatorList.fnArray[i];
                const args = operatorList.argsArray[i];
                
                // Track font changes
                if (fn === this.pdfjsLib.OPS.setFont && args.length >= 2) {
                    currentFont = {
                        name: args[0],
                        size: args[1]
                    };
                }
                
                // Track fill color (text color)
                if (fn === this.pdfjsLib.OPS.setFillRGBColor && args.length >= 3) {
                    currentFillColor = [args[0], args[1], args[2]];
                }
                
                // Track stroke color
                if (fn === this.pdfjsLib.OPS.setStrokeRGBColor && args.length >= 3) {
                    currentStrokeColor = [args[0], args[1], args[2]];
                }
                
                // When we encounter text operations, record the current state
                if (fn === this.pdfjsLib.OPS.showText || fn === this.pdfjsLib.OPS.showSpacedText) {
                    stateMap.set(i, {
                        font: currentFont ? {...currentFont} : null,
                        fillColor: [...currentFillColor],
                        strokeColor: [...currentStrokeColor]
                    });
                }
            }
            
            // Analyze each text item with its formatting context
            for (let i = 0; i < textContent.items.length; i++) {
                const item = textContent.items[i];
                
                // Get the text styling
                const style = this.analyzeTextItemStyle(item, stateMap);
                
                textAnalysis.push({
                    text: item.str,
                    style: style,
                    transform: item.transform,
                    fontName: item.fontName || '',
                    fontSize: item.fontSize || 0,
                    width: item.width || 0,
                    height: item.height || 0
                });
            }
            
        } catch (error) {
            console.warn('Error analyzing text formatting:', error);
            
            // Fallback: analyze without graphics state
            for (const item of textContent.items) {
                textAnalysis.push({
                    text: item.str,
                    style: this.analyzeTextItemStyle(item, new Map()),
                    transform: item.transform,
                    fontName: item.fontName || '',
                    fontSize: item.fontSize || 0,
                    width: item.width || 0,
                    height: item.height || 0
                });
            }
        }
        
        return textAnalysis;
    }

    /**
     * Analyze individual text item for track change styling
     * Uses text properties, font names, and colors instead of graphics lines
     */
    analyzeTextItemStyle(textItem, stateMap) {
        try {
            const text = textItem.str || '';
            const fontName = textItem.fontName || '';
            
            // 1. Font-based detection - Litera often uses specific fonts for markup
            if (this.isStrikethroughFont(fontName)) {
                return 'del';
            }
            
            if (this.isUnderlineFont(fontName)) {
                return 'ins';
            }
            
            // 2. Color-based detection - Look for red (deletion) or green/blue (insertion) text
            const colorStyle = this.analyzeTextColor(textItem, stateMap);
            if (colorStyle !== 'equal') {
                return colorStyle;
            }
            
            // 3. Text content analysis - Look for patterns in the text itself
            const contentStyle = this.analyzeTextContent(text);
            if (contentStyle !== 'equal') {
                return contentStyle;
            }
            
            // 4. Font size/style variations might indicate changes
            const styleVariation = this.analyzeStyleVariations(textItem);
            if (styleVariation !== 'equal') {
                return styleVariation;
            }
            
            return 'equal';
            
        } catch (error) {
            console.warn('Error analyzing text item style:', error);
            return 'equal';
        }
    }

    /**
     * Check if font name indicates strikethrough (deletion) formatting
     */
    isStrikethroughFont(fontName) {
        if (!fontName) return false;
        const name = fontName.toLowerCase();
        
        // Common patterns for strikethrough fonts in PDFs
        return name.includes('strike') ||
               name.includes('crossed') ||
               name.includes('deleted') ||
               name.includes('removed');
    }

    /**
     * Check if font name indicates underline (insertion) formatting  
     */
    isUnderlineFont(fontName) {
        if (!fontName) return false;
        const name = fontName.toLowerCase();
        
        // Common patterns for underline fonts in PDFs
        return name.includes('underline') ||
               name.includes('inserted') ||
               name.includes('added') ||
               name.includes('new');
    }

    /**
     * Analyze text color to detect track changes
     */
    analyzeTextColor(textItem, stateMap) {
        // This is a simplified color analysis
        // In a real implementation, you'd need to correlate text items with graphics state
        
        // Look for color hints in font name or other properties
        const fontName = (textItem.fontName || '').toLowerCase();
        
        // Some PDFs embed color information in font names
        if (fontName.includes('red') || fontName.includes('delete')) {
            return 'del';
        }
        
        if (fontName.includes('blue') || fontName.includes('green') || fontName.includes('insert')) {
            return 'ins';
        }
        
        return 'equal';
    }

    /**
     * Analyze text content for markup patterns
     */
    analyzeTextContent(text) {
        if (!text || text.trim().length === 0) return 'equal';
        
        // Look for common track change text patterns
        // This is heuristic-based and may need refinement
        
        // Very short connector words that are often insertions
        const commonInsertions = ['and', 'or', 'the', 'a', 'an', 'to', 'of', 'in', 'on', 'at', 'by', 'for'];
        const trimmedText = text.trim().toLowerCase();
        
        if (commonInsertions.includes(trimmedText) && text.length <= 4) {
            // Small words are more likely to be insertions
            return 'ins';
        }
        
        return 'equal';
    }

    /**
     * Look for style variations that might indicate changes
     */
    analyzeStyleVariations(textItem) {
        // This would analyze font size changes, bold/italic variations, etc.
        // For now, return equal - this can be enhanced based on actual PDF patterns
        return 'equal';
    }

    /**
     * Generate HTML diff from styled text for further processing
     */
    generateHtmlDiff(styledText) {
        // Sort text items by position to reconstruct reading order
        const sortedText = [...styledText].sort((a, b) => {
            const y1 = a.transform[5];
            const y2 = b.transform[5];
            const x1 = a.transform[4];
            const x2 = b.transform[4];
            
            // First sort by Y (top to bottom, but PDF Y is inverted)
            if (Math.abs(y1 - y2) > 8) { // Different lines
                return y2 - y1; // Higher Y coordinate comes first in PDF
            } else {
                // Same line, sort by X (left to right)
                return x1 - x2;
            }
        });
        
        let html = '<div style="font-family: serif; white-space: pre-wrap;">';
        let currentLineY = null;
        let addedSpacing = false;
        
        sortedText.forEach((item, index) => {
            const y = item.transform[5];
            const text = this.escapeHtml(item.text);
            
            // Add line breaks for new lines
            if (currentLineY !== null && Math.abs(y - currentLineY) > 8) {
                html += '<br>\n';
                addedSpacing = true;
            }
            
            // Add spacing between words on same line
            if (index > 0 && !addedSpacing && currentLineY !== null && 
                Math.abs(y - currentLineY) <= 8) {
                html += ' ';
            }
            
            currentLineY = y;
            addedSpacing = false;
            
            // Wrap text based on detected style
            if (item.style === 'ins') {
                html += `<span style="text-decoration: underline; color: #16a34a;">${text}</span>`;
            } else if (item.style === 'del') {
                html += `<span style="text-decoration: line-through; color: #dc2626;">${text}</span>`;
            } else {
                html += text;
            }
        });
        
        html += '</div>';
        return html;
    }

    /**
     * Escape HTML special characters
     */
    escapeHtml(text) {
        return text
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    }
}

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = PdfAnalyzer;
} else {
    window.PdfAnalyzer = PdfAnalyzer;
}